# -*- coding: utf-8 -*-
"""Group_Project (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dhhbV_UsxZA8P9x3mcctjqQ_V-QNlE8U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("bank_transactions_data_2.csv")
df.head()

cols = [
    "AccountID",
    "TransactionDate",
    "PreviousTransactionDate",
    "TransactionAmount",
    "TransactionType",
    "Channel",
    "TransactionDuration",
    "LoginAttempts",
    "AccountBalance",
    "CustomerAge"
]

data = df[cols].copy()

data["TransactionDate"] = pd.to_datetime(data["TransactionDate"])
data["PreviousTransactionDate"] = pd.to_datetime(data["PreviousTransactionDate"])

data["TimeGap"] = (
    data["TransactionDate"] - data["PreviousTransactionDate"]
).dt.total_seconds() / 3600

print("Shape:", data.shape)
print("\nMissing Values:\n", data.isnull().sum())
data.describe()

data = data[data["TransactionAmount"] > 0]

# Fill missing temporal gaps
data["TimeGap"] = data["TimeGap"].fillna(data["TimeGap"].median())

# Cap outliers (TransactionAmount)
Q1 = data["TransactionAmount"].quantile(0.25)
Q3 = data["TransactionAmount"].quantile(0.75)
IQR = Q3 - Q1

data = data[
    (data["TransactionAmount"] >= Q1 - 1.5*IQR) &
    (data["TransactionAmount"] <= Q3 + 1.5*IQR)
]

data["HighValueTxn"] = np.where(
    data["TransactionAmount"] > data["TransactionAmount"].quantile(0.90), 1, 0
)

# Frequent login flag
data["HighLoginAttempts"] = np.where(data["LoginAttempts"] > 3, 1, 0)

# Short time gap flag
data["RapidTxn"] = np.where(data["TimeGap"] < 1, 1, 0)

# Balance ratio
data["TxnToBalanceRatio"] = data["TransactionAmount"] / data["AccountBalance"]

num_cols = [
    "TransactionAmount",
    "TransactionDuration",
    "LoginAttempts",
    "TimeGap",
    "TxnToBalanceRatio"
]

for col in num_cols:
    plt.figure()
    plt.hist(data[col], bins=30)
    plt.title(f"{col} Distribution")
    plt.show()

plt.figure()
plt.boxplot(data["TransactionAmount"])
plt.title("Transaction Amount Outliers")
plt.show()

plt.figure()
data["Channel"].value_counts().plot(kind="bar")
plt.title("Channel Distribution")
plt.show()

plt.figure()
plt.scatter(data["TransactionAmount"], data["AccountBalance"])
plt.xlabel("Transaction Amount")
plt.ylabel("Account Balance")
plt.title("Transaction vs Balance")
plt.show()

plt.figure()
plt.scatter(data["TimeGap"], data["TransactionAmount"])
plt.xlabel("Time Gap (hrs)")
plt.ylabel("Transaction Amount")
plt.title("Time Gap vs Transaction Amount")
plt.show()

corr = data.corr(numeric_only=True)

plt.figure(figsize=(10,8))
plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.title("Multivariate Correlation Matrix")
plt.show()

data["RiskScore"] = (
    data["HighValueTxn"] * 3 +
    data["HighLoginAttempts"] * 2 +
    data["RapidTxn"] * 2 +
    data["TxnToBalanceRatio"]
)

data[["AccountID", "TransactionAmount", "RiskScore"]].head()

plt.figure()
plt.hist(data["RiskScore"], bins=30)
plt.title("Risk Score Distribution")
plt.show()

data["RiskLevel"] = pd.cut(
    data["RiskScore"],
    bins=[-1, 2, 5, np.inf],
    labels=["Low", "Medium", "High"]
)

data["RiskLevel"].value_counts()

features = [
    "TransactionAmount",
    "TransactionDuration",
    "LoginAttempts",
    "AccountBalance",
    "TimeGap",
    "TxnToBalanceRatio"
]

X = data[features]

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

iso_forest = IsolationForest(
    n_estimators=100,
    contamination=0.05,
    random_state=42
)

data["IF_Anomaly"] = iso_forest.fit_predict(X_scaled)

data["IF_Anomaly"] = data["IF_Anomaly"].map({1: 0, -1: 1})
data["IF_Anomaly"].value_counts()

plt.figure()
plt.scatter(
    data["TransactionAmount"],
    data["AccountBalance"],
    c=data["IF_Anomaly"]
)
plt.xlabel("Transaction Amount")
plt.ylabel("Account Balance")
plt.title("Isolation Forest Anomaly Detection")
plt.show()

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_scaled.shape[1]

input_layer = Input(shape=(input_dim,))
encoded = Dense(16, activation="relu")(input_layer)
encoded = Dense(8, activation="relu")(encoded)

decoded = Dense(16, activation="relu")(encoded)
decoded = Dense(input_dim, activation="linear")(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)
autoencoder.compile(
    optimizer="adam",
    loss="mse"
)

autoencoder.fit(
    X_scaled,
    X_scaled,
    epochs=20,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

reconstructions = autoencoder.predict(X_scaled)
reconstruction_error = np.mean(np.square(X_scaled - reconstructions), axis=1)

data["AE_Error"] = reconstruction_error

threshold = np.percentile(reconstruction_error, 95)

data["AE_Anomaly"] = np.where(
    reconstruction_error > threshold, 1, 0
)

data["AE_Anomaly"].value_counts()

plt.figure()
plt.hist(data["AE_Error"], bins=30)
plt.axvline(threshold)
plt.title("Autoencoder Reconstruction Error")
plt.show()

data["FinalRiskScore"] = (
    data["RiskScore"] +
    data["IF_Anomaly"] * 3 +
    data["AE_Anomaly"] * 3
)

data["FinalRiskLevel"] = pd.cut(
    data["FinalRiskScore"],
    bins=[-1, 4, 8, np.inf],
    labels=["Low", "Medium", "High"]
)

data["FinalRiskLevel"].value_counts()

plt.figure()
data["FinalRiskLevel"].value_counts().plot(kind="bar")
plt.title("Final Risk Level Distribution")
plt.show()

print("===== DATASET SUMMARY =====")
print(f"Total Transactions: {data.shape[0]}")
print(f"Total Features Used: {data.shape[1]}")
print("\nRisk Level Distribution:")
print(data["FinalRiskLevel"].value_counts())
print("\n===== BEHAVIORAL INDICATORS =====")
print("High Value Transactions:", data["HighValueTxn"].sum())
print("Rapid Transactions:", data["RapidTxn"].sum())
print("High Login Attempts:", data["HighLoginAttempts"].sum())
print("\n===== ANOMALY DETECTION RESULTS =====")
print("Isolation Forest Anomalies:", data["IF_Anomaly"].sum())
print("Autoencoder Anomalies:", data["AE_Anomaly"].sum())
print("\n===== RISK SCORE STATISTICS =====")
print(data["FinalRiskScore"].describe())
print("\n===== SAMPLE HIGH-RISK TRANSACTIONS =====")
data[data["FinalRiskLevel"] == "High"][
    ["AccountID", "TransactionAmount", "RiskScore", "FinalRiskScore"]
].head()
customer_risk = (
    data.groupby("AccountID")["FinalRiskScore"]
    .mean()
    .reset_index()
    .sort_values(by="FinalRiskScore", ascending=False)
)

print("\n===== TOP HIGH-RISK CUSTOMERS =====")
customer_risk.head()
plt.figure()
data["FinalRiskLevel"].value_counts().plot(kind="pie", autopct="%1.1f%%")
plt.title("Overall Risk Level Distribution")
plt.show()

# Filter for Medium and High risk only
significant_risks = data[data['FinalRiskLevel'].isin(['High'])]

# Sort by FinalRiskScore descending so the most dangerous are at the top
significant_risks_sorted = significant_risks.sort_values(by='FinalRiskScore', ascending=False)

# Display relevant columns
display_cols = ['AccountID', 'TransactionAmount', 'FinalRiskScore', 'FinalRiskLevel', 'multimodal_reason']

# Show the results (e.g., top 10 most critical)
significant_risks_sorted[display_cols].head(10)

import streamlit as st
import numpy as np
import pandas as pd
import plotly.express as px

st.header("📈 Temporal Risk Score Evolution")

np.random.seed(42)
time_index = pd.date_range(start="2024-01-01", periods=50, freq="H")
risk_scores_ts = np.cumsum(np.random.normal(0.02, 0.05, 50)).clip(0, 1)

risk_df_ts = pd.DataFrame({
    "Time": time_index,
    "Risk Score": risk_scores_ts
})

fig_ts = px.line(
    risk_df_ts,
    x="Time",
    y="Risk Score",
    title="Risk Score Drift Over Time"
)

st.plotly_chart(fig_ts, use_container_width=True)
st.caption("Rising trends indicate escalating behavioral risk.")

st.header("🧠 Multi-Modal Risk Contribution")

modalities = ["Behavioral", "Network", "Transactional", "Temporal", "Device"]
contributions = np.abs(np.random.randn(5))
contributions = contributions / contributions.sum()

contrib_df = pd.DataFrame({
    "Modality": modalities,
    "Contribution": contributions
})

fig_modal = px.pie(
    contrib_df,
    names="Modality",
    values="Contribution",
    title="Risk Score Contribution by Modality"
)

st.plotly_chart(fig_modal, use_container_width=True)
st.caption("Illustrates explainability across multiple behavioral signals.")

st.header("🧩 Behavioral Anomaly Clustering")

cluster_points = 300
cluster_data = pd.DataFrame({
    "Dim_1": np.random.randn(cluster_points),
    "Dim_2": np.random.randn(cluster_points),
    "Cluster": np.random.choice(["Low Risk", "Medium Risk", "High Risk"], cluster_points)
})

fig_cluster = px.scatter(
    cluster_data,
    x="Dim_1",
    y="Dim_2",
    color="Cluster",
    title="Behavioral Archetypes via Unsupervised Clustering",
    opacity=0.7
)

st.plotly_chart(fig_cluster, use_container_width=True)
st.caption("Distinct clusters represent different anomaly behavior patterns.")

st.header("⚙️ Risk Threshold Simulation")

threshold = st.slider(
    "Select Risk Threshold",
    min_value=0.0,
    max_value=1.0,
    value=0.6,
    step=0.05
)

false_positives = int((1 - threshold) * 100)
missed_anomalies = int(threshold * 60)

st.metric("False Positives", false_positives)
st.metric("Missed Anomalies", missed_anomalies)

st.caption("Helps tune operational thresholds for alert generation.")

st.header("⏳ Early-Warning Risk Forecast")

forecast_horizon = st.selectbox(
    "Forecast Horizon",
    ["Next 1 Hour", "Next 24 Hours", "Next 7 Days"]
)

forecast_risk = np.clip(np.random.normal(0.7, 0.1), 0, 1)

st.metric(
    label=f"Predicted Risk ({forecast_horizon})",
    value=f"{forecast_risk:.2f}"
)

st.progress(int(forecast_risk * 100))
st.caption("Forecasted probability enables proactive anomaly mitigation.")